Update README.md :rocket:
SwifterSwift/SwifterSwift pull request #1030
Opened 2022-08-03 11:03 UTC by stavares843

## Checklist

- [ ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 5.0.
- [ ] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2022-08-03 21:59 UTC, guykogus requested changes
@stavares843 why are you changing these links?

2022-08-03 22:21 UTC, stavares843 commented
<img width="1057" alt="Captura de ecrã 2022-08-03, às 23 21 18" src="https://user-images.githubusercontent.com/29093946/182722494-bb2221c5-ee15-488f-a71c-ad1d58ddc410.png">

<img width="850" alt="Captura de ecrã 2022-08-03, às 23 21 12" src="https://user-images.githubusercontent.com/29093946/182722499-24c1f503-85ce-49c5-a35a-93ef6109bb9c.png">

2022-08-04 06:48 UTC, cdoky commented
@guykogus 
First, are we still using Slack? If we are, we need to update the link. If not, then we should remove this link.

2022-08-09 00:13 UTC, LucianoPAlmeida commented
> @guykogus
> First, are we still using Slack? If we are, we need to update the link. If not, then we should remove this link.

We still do, there is not much going on there for a while but is still there :)

2022-11-02 13:10 UTC, stavares843 commented
👋

2022-11-02 17:52 UTC, LucianoPAlmeida commented on README.md
> +## Slack Channel: [![Slack](https://img.shields.io/badge/Slack-SwifterSwift-green.svg)](https://join.slack.com/t/swifterswift/shared_invite/zt-s6dl4g2e-R5V5baIawGpdUz2heShjiQ)
Shared invite link normally expires, so let's go with this
```suggestion
## Slack Channel: [![Slack](https://img.shields.io/badge/Slack-SwifterSwift-green.svg)](https://swifterswift.slack.com)
```

2022-11-02 17:53 UTC, LucianoPAlmeida commented on README.md
> +It is always nice to talk with other people using SwifterSwift and exchange experiences, so come [join our Slack channel](https://join.slack.com/t/swifterswift/shared_invite/zt-s6dl4g2e-R5V5baIawGpdU
Here too
```suggestion
It is always nice to talk with other people using SwifterSwift and exchange experiences, so come [join our Slack channel](https://swifterswift.slack.com).
```

2022-11-02 18:58 UTC, LucianoPAlmeida approved these changes

2022-11-08 20:52 UTC, guykogus approved these changes

2022-11-09 00:15 UTC, merged

2022-11-09 00:15 UTC, SD10 commented
Thank you for contributing to SwifterSwift! I've invited you to join the SwifterSwift GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md). Feel free to reach out if you have any questions! 😃

2022-11-09 23:08 UTC, stavares843 commented
thanks! 🎉