fix nearestTenMinutes behavior
SwifterSwift/SwifterSwift pull request #1034
Opened 2022-08-09 19:03 UTC by mmdock

fix nearestTenMinutes rounding behavior to behavior like nearestHalfHour

<img width="399" alt="Screen Shot 2022-08-09 at 12 01 57 PM" src="https://user-images.githubusercontent.com/2423465/183740196-bdba1a2c-75d9-4010-a54c-acf7990f182e.png">

As can be seen in the screenshot, nearestTenMinutes, if the minute is an interval of 5, rounds down.  nearestHalfHour, rounds up. 

This PR aligns behavior expectations on similarly named computed variables

2022-08-10 01:24 UTC, LucianoPAlmeida commented
CI is failing due to a tool issue, it was a tool we really weren't using so it was removed. Just update with master =]

2022-08-10 01:27 UTC, LucianoPAlmeida commented
Regarding the PR itself, I really don't have an opinion about that, so I'll let others take on it. But some thoughts on top of my head:
* Changing this modifies behavior of the method in which someone may rely on, so that will be breaking (not sure how much breaking)
* If we are moving forward with this, can we add some testing cases to exercise that flow?

2022-08-16 21:25 UTC, mmdock commented
> Regarding the PR itself, I really don't have an opinion about that, so I'll let others take on it. But some thoughts on top of my head:
> 
> * Changing this modifies behavior of the method in which someone may rely on, so that will be breaking (not sure how much breaking)
> * If we are moving forward with this, can we add some testing cases to exercise that flow?

I can make some updates in a few days with testing cases, etc

2022-08-19 01:08 UTC, mmdock commented
> * Changing this modifies behavior of the method in which someone may rely on, so that will be breaking (not sure how much breaking)

tbh, I would regard this as a bug in the initial behavior expectations.  

I would go so far as to say the `nearestQuarterHour` and `nearestFiveMinutes` are also inaccurate based on the name descriptor. 

So in nearestFive minutes, if I have "5:52:50 PM" it would round to "5:50:00 PM".  To me that is inaccurate, since the date is actually closer to "5:55:00 PM"

2022-08-30 13:13 UTC, LucianoPAlmeida reviewed
Can you add a change log entry? I think this looks fine =]

2022-09-09 06:30 UTC, mmdock commented
> Can you add a change log entry? I think this looks fine =]

sure! was backpacking, will wrap this up tomorrow :)

2022-09-30 12:26 UTC, guykogus requested changes
Nitpick

2022-09-30 12:26 UTC, guykogus commented on CHANGELOG.md
> +  - fixed incorrect calculation in `nearestTenMinutes` , to align with other `nearest*` date calculations.  [#1034](https://github.com/SwifterSwift/SwifterSwift/pull/1034) by [mmdock](https://github.
```suggestion
  - Fixed incorrect calculation in `nearestTenMinutes` to align with other `nearest*` date calculations. [#1034](https://github.com/SwifterSwift/SwifterSwift/pull/1034) by [mmdock](https://github.com/mmdock)
```

2022-10-06 03:16 UTC, LucianoPAlmeida approved these changes

2022-10-08 15:19 UTC, guykogus approved these changes

2022-10-08 19:07 UTC, merged