String [safeFrom:] and [safeTo:]
SwifterSwift/SwifterSwift pull request #1067
Opened 2022-12-24 11:07 UTC by RomanPodymov

🚀

Hello.
Thank you for SwifterSwift.
Fix #1066.

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.0.
- [x] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2023-01-07 17:02 UTC, viktart commented
Hello! 👋
My suggestion is to rewrite these two functions into one `subscript(safe range: Range<Int>) -> String.SubSequence`

2023-01-07 17:14 UTC, viktart requested changes
Hello! 👋
My suggestion is to rewrite these two functions into `subscript(safe range: PartialRangeFrom<Int>) -> String` and `subscript(safe range: PartialRangeThrough<Int>) -> String` so they could be used like that:
`s[safe: 2...]
s[safe: ...3]`

2023-01-09 11:30 UTC, LucianoPAlmeida commented
> Hello! 👋
> My suggestion is to rewrite these two functions into `subscript(safe range: PartialRangeFrom<Int>) -> String` and `subscript(safe range: PartialRangeThrough<Int>) -> String` so they could be used like that:
> `s[safe: 2...] s[safe: ...3]`

Agreed, but I think we have that already in a generic way https://github.com/SwifterSwift/SwifterSwift/blob/efeb11aabfeae672461472e5a7a173b5da545895/Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift#L627
So those additional extensions wouldn't add any functionality

2023-01-09 12:09 UTC, RomanPodymov commented
> > Hello! 👋
> > My suggestion is to rewrite these two functions into `subscript(safe range: PartialRangeFrom<Int>) -> String` and `subscript(safe range: PartialRangeThrough<Int>) -> String` so they could be used like that:
> > `s[safe: 2...] s[safe: ...3]`
> 
> Agreed, but I think we have that already in a generic way
> 
> https://github.com/SwifterSwift/SwifterSwift/blob/efeb11aabfeae672461472e5a7a173b5da545895/Sources/SwifterSwift/SwiftStdlib/StringExtensions.swift#L627
> 
> 
> So those additional extensions wouldn't add any functionality

Hello @LucianoPAlmeida @viktart 
I see there is already `subscript<R>(safe range: R) -> String? where R: RangeExpression, R.Bound == Int`, but `"Hello world"[safe: 6...]` returns `nil`.

2023-01-09 12:21 UTC, LucianoPAlmeida commented
> Hello @LucianoPAlmeida @viktart 
> 
> I see there is already `subscript<R>(safe range: R) -> String? where R: RangeExpression, R.Bound == Int`, but `"Hello world"[safe: 6...]` returns `nil`.

2023-01-09 18:10 UTC, closed without merging

2023-01-11 10:23 UTC, viktart commented
https://github.com/SwifterSwift/SwifterSwift/issues/1071