Hide bottom bar
SwifterSwift/SwifterSwift pull request #1117
Opened 2023-06-20 15:37 UTC by imdkhairul

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.0.
- [x] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2023-06-21 15:13 UTC, guykogus requested changes

2023-06-21 15:13 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationControllerExtensions.swift
> +    func pushViewController(_ viewController: UIViewController, hideBottomBar:Bool){
```suggestion
    func pushViewController(_ viewController: UIViewController, hidesBottomBar: Bool, animated: Bool) {
```

2023-06-21 15:13 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    func testHideBottomBar(){
```suggestion
    func testHideBottomBar() {
```

2023-06-21 16:06 UTC, imdkhairul commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    }
Sure

2023-06-27 17:19 UTC, guykogus requested changes

2023-06-27 17:19 UTC, guykogus commented on CHANGELOG.md
> +**UINavigationController**
```suggestion
- **UINavigationController**
```

2023-06-27 17:19 UTC, guykogus commented on CHANGELOG.md
> +  - Added `pushViewController(_:hidesBottomBar:animated:)` for hiding the bottom bar when pushing any `UIViewController`. [#1117](https://github.com/SwifterSwift/SwifterSwift/issues/1117) [imdkhairul
```suggestion
  - Added `pushViewController(_:hidesBottomBar:animated:)` for hiding the bottom bar when pushing any `UIViewController`. [#1117](https://github.com/SwifterSwift/SwifterSwift/issues/1117) by [imdkhairul](https://github.com/imdkhairul)
```

2023-06-27 17:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationControllerExtensions.swift
> +    func pushViewController(_ viewController: UIViewController, hideBottomBar:Bool, animated:Bool) {
Please be aware of spaces and change from `hideBottomBar` to `hidesBottomBar`
```suggestion
    /// SwifterSwift: Pushes a view controller while hiding or showing the bottom bar.
    ///
    /// - Parameters:
    ///   - viewController: The view controller to push.
    ///   - hidesBottomBar: If `true`, hides the bottom bar (e.g. tab bar).
    ///   - animated: Specify `true` to animate the transition.
    func pushViewController(_ viewController: UIViewController, hidesBottomBar: Bool, animated: Bool) {
```

2023-06-27 17:19 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +
If you want to test something with a delay, you need to wait for an expectation.
Also, you probably don't even need the delay for the async call, if you set `animated: false`
```suggestion
        let expectation = XCTestExpectation(description: "Tab bar hidden")
        DispatchQueue.main.async {
            XCTAssert(tabVC.tabBar.isHidden)
            expectation.fulfill()
        }
        wait(for: [expectation], timeout: 0.1)
```

2023-06-27 17:19 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +        navigationController.pushViewController(vcToPush, hideBottomBar: true, animated: true)
Don't animate in unit tests.
```suggestion
        navigationController.pushViewController(vcToPush, hideBottomBar: true, animated: false)
```

2023-06-27 20:19 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +
Actually, if you don't animate then you may not need the `async` call altogether and can just run the test. Try that first.

2023-07-03 15:28 UTC, guykogus requested changes

2023-07-03 15:28 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationControllerExtensions.swift
> +    func pushViewController(_ viewController: UIViewController, hidesBottomBar: Bool, animated: Bool) {
Remove extra empty line
```suggestion
    ///   - animated: Specify `true` to animate the transition.
    func pushViewController(_ viewController: UIViewController, hidesBottomBar: Bool, animated: Bool) {
```

2023-07-03 16:10 UTC, guykogus requested changes

2023-07-03 16:10 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationControllerExtensions.swift
> +    /// SwifterSwift: Pushes a view controller while hiding or showing the bottom bar.
```suggestion
#if !os(tvOS)
    /// SwifterSwift: Pushes a view controller while hiding or showing the bottom bar.
```

2023-07-03 16:10 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationControllerExtensions.swift
> +    }
```suggestion
    }
#endif
```

2023-07-03 16:10 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    func testHideBottomBar() {
```suggestion
#if !os(tvOS)
    func testHideBottomBar() {
```

2023-07-03 16:10 UTC, guykogus commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    }
```suggestion
    }
#endif
```

2023-07-03 16:12 UTC, guykogus commented
@imdkhairul `hidesBottomBarWhenPushed` is not available for tvOS, so we need to disable the function and tests there.

2023-07-03 16:41 UTC, imdkhairul commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    }
@guykogus Disabled for tvOS

2023-07-03 16:41 UTC, imdkhairul commented on Tests/UIKitTests/UINavigationControllerExtensionsTests.swift
> +    func testHideBottomBar() {
@guykogus Disabled for tvOS

2023-07-03 17:48 UTC, guykogus approved these changes

2023-09-30 11:14 UTC, merged