Add makeCircle function inside UIViewExtensions
SwifterSwift/SwifterSwift pull request #1165
Opened 2024-01-14 15:00 UTC by happyduck-git

Add a function that makes a UIView instance a circular shape.
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.6.
- [x] New extensions support iOS 12.0+ / tvOS 12.0+ / macOS 10.13+ / watchOS 4.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2024-01-20 02:18 UTC, happyduck-git commented on Tests/UIKitTests/UIViewExtensionsTests.swift
> +        let view = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 50))
I assumed the situation when the frame is already set before the `makeCircle` method is called. Since it may make some confusions, I can change that!

2024-01-20 17:18 UTC, guykogus requested changes

2024-01-20 17:18 UTC, guykogus commented on CHANGELOG.md
> +  - Added `makeCircle()` method to make the view circular. [#1165](https://github.com/SwifterSwift/SwifterSwift/pull/1165) by [happyduck-git](https://github.com/happyduck-git)
```suggestion
  - Added `makeCircle(diameter:)` method to make the view circular. [#1165](https://github.com/SwifterSwift/SwifterSwift/pull/1165) by [happyduck-git](https://github.com/happyduck-git)
```

2024-01-20 17:18 UTC, guykogus commented on Tests/UIKitTests/UIViewExtensionsTests.swift
> +        view.makeCircle(100)
```suggestion
        view.makeCircle(diameter: 100)
```

2024-01-23 00:52 UTC, LucianoPAlmeida approved these changes

2024-01-23 07:59 UTC, guykogus approved these changes

2024-01-23 07:59 UTC, merged