Improved documentation to borderColor in NSViewExtensions
SwifterSwift/SwifterSwift pull request #1212
Opened 2024-09-07 06:43 UTC by herlandro

🚀

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.6.
- [x] New extensions support iOS 12.0+ / tvOS 12.0+ / macOS 10.13+ / watchOS 4.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2024-09-10 15:25 UTC, guykogus requested changes
I don't think we really need an improvement for this documentation. It's fairly straightforward...

2024-09-10 15:25 UTC, guykogus commented on Sources/SwifterSwift/AppKit/NSViewExtensions.swift
> +    ///    view.borderColor = NSColor.red
Can't you just do this?
```suggestion
    ///    view.borderColor = .red
```

2024-09-10 15:25 UTC, guykogus commented on Sources/SwifterSwift/AppKit/NSViewExtensions.swift
> +    /// - Returns: The border color of the view as `NSColor`.
You don't need a `Returns` for a computed property.

2024-09-10 15:32 UTC, herlandro commented
> I don't think we really need an improvement for this documentation. It's fairly straightforward...

Ok, No problem. There is some place on your project that you need help and that I can help?

2024-12-13 15:22 UTC, guykogus commented
@herlandro sorry for the very late reply. If you want to help please check the [Issues](https://github.com/SwifterSwift/SwifterSwift/issues) and see what you can take. Thanks :)

2024-12-13 15:22 UTC, closed without merging