fix bug: Rotated UIImage lose origin scale and blured.
SwifterSwift/SwifterSwift pull request #904
Opened 2020-09-15 08:42 UTC by yanpanpan

Fix bug. When UIImage rotated, it lost origin scale. 

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.0.
- [x] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2020-09-17 08:54 UTC, guykogus requested changes
Please add a CHANGELOG entry and perhaps update the tests

2020-09-21 02:55 UTC, yanpanpan commented
CHANGELOG entry is added, all tests is OK and passed.

2020-09-21 07:37 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/UIKit/UIImageExtensions.swift
> +        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, false, scale)
```suggestion
        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, /*opaque=*/false, scale)
```

2020-09-21 07:38 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/UIKit/UIImageExtensions.swift
> +        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, false, scale)
Just to make it easier for the reader ... I had to go to docs to remember what `false` meant 
```suggestion
        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, /*opaque=*/false, scale)
```

2020-09-21 08:53 UTC, LucianoPAlmeida submitted a review, later dismissed
LGTM! Thanks :)

2020-09-21 18:35 UTC, guykogus approved these changes
I personally strongly dislike the `/*opaque*/` comments, but 🤷‍♂️

2020-09-21 21:22 UTC, LucianoPAlmeida commented
> I personally strongly dislike the `/*opaque*/` comments, but 🤷‍♂️

Ahh feel free to request changes, I personally find useful for literals and use a lot at work with C++ because functions don't have labels there, so we use this pattern to make it easier to read at call site what the parameter means e.g. `p->function(param, /*argument=*/nullptr)` ... 
But feel free to revert ... it's not that important 

@yanpanpan it is good to go can you just revert this so we can merge? :)

2020-09-21 22:20 UTC, guykogus requested changes
Ok fine, let's get rid of it...

2020-09-21 22:20 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UIImageExtensions.swift
> +        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, /*opaque=*/false, scale)
```suggestion
        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, false, scale)
```

2020-09-21 22:20 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UIImageExtensions.swift
> +        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, /*opaque=*/false, scale)
```suggestion
        UIGraphicsBeginImageContextWithOptions(roundedDestRect.size, false, scale)
```

2020-09-22 02:10 UTC, yanpanpan commented
> > I personally strongly dislike the `/*opaque*/` comments, but 🤷‍♂️
> 
> Ahh feel free to request changes, I personally find useful for literals and use a lot at work with C++ because functions don't have labels there, so we use this pattern to make it easier to read at call site what the parameter means e.g. `p->function(param, /*argument=*/nullptr)` ...
> But feel free to revert ... it's not that important
> 
> @yanpanpan it is good to go can you just revert this so we can merge? :)

I personally  think removing `/*opaque*/` looks more `SwifterSwift`. Thanks everyone. Revert is done.

2020-09-22 02:11 UTC, LucianoPAlmeida approved these changes
Thank you!

2020-09-22 07:52 UTC, guykogus approved these changes

2020-09-22 07:52 UTC, merged

2020-09-22 07:53 UTC, SD10 commented
Thank you for contributing to SwifterSwift! I've invited you to join the SwifterSwift GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md). Feel free to reach out if you have any questions! 😃