refactor: base operators in in-place ones
SwifterSwift/SwifterSwift pull request #919
Opened 2020-11-05 13:17 UTC by sk-

Operators should be implemented based on their in-place variants, not the other way around. In that way in-place operations won't allocate any new objects.

See #916 for more details.

This PR allows us to reenable the swiftlint rule shorthand_operator. It also refactors other operators to use their in-place variant to reduce code duplication.

## Checklist

- [ ] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [ ] New extensions are written in Swift 5.0.
- [ ] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [ ] I have added tests for new extensions, and they passed.
- [ ] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [ ] All extensions are declared as **public**.
- [ ] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2020-11-05 13:19 UTC, sk- commented
I changed all the other operators (except for the ones in `NSAttributedString`) to be based on the in-place operators. Let me know what you think.

2020-11-05 23:50 UTC, LucianoPAlmeida reviewed
Let's just change the places that use `-`, `+`, `*`, `/`... inside an `...=`, which I believe are the ones which the rule applies. The other let's leave as it was before :)

2020-11-05 23:50 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
> -        return CGPoint(x: lhs.x - rhs.x, y: lhs.y - rhs.y)
TBH I think this is better the way it was ... to me it is simpler :)

2020-11-05 23:50 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
> -        return CGPoint(x: lhs.x + rhs.x, y: lhs.y + rhs.y)
This one too ...

2020-11-05 23:50 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
> -        lhs = lhs + rhs
Nice!

2020-11-05 23:50 UTC, LucianoPAlmeida commented on Sources/SwifterSwift/CoreGraphics/CGPointExtensions.swift
> +        var result = point
Here too ...

2020-11-05 23:51 UTC, LucianoPAlmeida commented
Also, don't forget the changelog entry :)

2020-11-08 19:45 UTC, guykogus requested changes
Unfortunately code duplication is inevitable in this project. One of the conditions is that any function should be copyable as-is, without having to copy any other functions*. This means that you can't use the in-place variants.

In some places it's also a lot more inefficient. E.g. in `CGPoint.+(lhs:rhs:)` instead of creating the new object directly with the added values, you're creating a copy of an object, jumping to another function in order to add the values via a reference and then jump back to return the updated object. It's longer, less efficient code that violates a primary directive of the project.

On the other hand, the updates to the in-place functions, e.g. `CGPoint.+=(lhs:rhs:)`, are much better! I agree that they're more efficient and they also fix the copying issue mentioned.

---

\* In the past this wasn't enforced so it exists in some places, but we don't want it to happen any more**.

** Even though I'm personally not in favour of it.

2020-11-08 21:18 UTC, LucianoPAlmeida commented
> One of the conditions is that any function should be copyable as-is, without having to copy any other functions*. This means that you can't use the in-place variants.

IMO, non-complex arithmetic operators such `+` and `+=` can be an exception to this rule because one is always a mutating complement of the other, and people likely copying both anyways. I think that is the reason we allowed this... 

> In some places it's also a lot more inefficient. E.g. in CGPoint.+(lhs:rhs:) 

+ 1

2020-11-09 11:06 UTC, guykogus commented
> IMO, non-complex arithmetic operators such `+` and `+=` can be an exception to this rule because one is always a mutating complement of the other, and people likely copying both anyways. I think that is the reason we allowed this...

I'm more than happy to make an exception here. My other points still stand though :)

2020-11-18 18:39 UTC, sk- commented
Closing as I don't have the time to address the requirements. Feel free to reuse portions of this PR.

2020-11-18 18:39 UTC, closed without merging

2020-11-19 01:42 UTC, LucianoPAlmeida commented
> Closing as I don't have the time to address the requirements. Feel free to reuse portions of this PR.

Hey @sk- , no worries!
But feel free to get back to it when possible in the future :)