Add `init?(argbHexString:)` to support the common ARGB format used in Android
SwifterSwift/SwifterSwift pull request #971
Opened 2021-07-05 18:49 UTC by yonat

🚀

## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 5.0.
- [x] New extensions support iOS 10.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+, or use `@available` if not.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

2021-07-06 16:52 UTC, guykogus requested changes
Nice. Just a couple of small points.

2021-07-06 16:52 UTC, guykogus commented on Sources/SwifterSwift/Shared/ColorExtensions.swift
> +            string.forEach { str.append(String(repeating: String($0), count: 2)) }
Prefer `for-in` over `forEach` whenever possible.

2021-07-06 16:52 UTC, guykogus commented on Sources/SwifterSwift/Shared/ColorExtensions.swift
> +        let alpha = hasAlpha ? (hexValue >> 24) & 0xFF : 0xFF
```suggestion
        guard let hexValue = Int(string, radix: 16) else { return nil }

        let hasAlpha = string.count == 8
        let alpha = hasAlpha ? (hexValue >> 24) & 0xFF : 0xFF
```

2021-07-07 04:31 UTC, yonat commented
Thanks @guykogus , fixed.

2021-07-07 06:34 UTC, guykogus approved these changes

2021-07-07 13:46 UTC, merged