Fixing issue #970 - NSDecimalNumber extension
SwifterSwift/SwifterSwift pull request #973
Opened 2021-07-06 15:41 UTC by spneshaei

Fixing issue #970 - Added NSDecimalNumber extension with support for most-used operators

The necessary tests are also provided

2021-07-06 23:38 UTC, LucianoPAlmeida commented
Thanks for your contribution @spneshaei
We'll take a look as soon as possible  =]

2021-07-19 23:48 UTC, LucianoPAlmeida reviewed
It seems reasonable to me, just not sure about adding conformance because some guides of the project(although I think this wouldn't hurt), so I'm not sure. @guykogus and @omaralbeik thoughts? 
Also, if we decide to land this can you add a changelog entry?

2021-07-19 23:48 UTC, LucianoPAlmeida commented on Tests/FoundationTests/NSDecimalNumberExtensionsTests.swift
> +// NSDecimalNumberExtensionsTests.swift - Copyright 2020 SwifterSwift
```suggestion
// NSDecimalNumberExtensionsTests.swift - Copyright 2021 SwifterSwift
```

2021-07-21 17:51 UTC, guykogus requested changes
Nice addition, thanks :)
A few comments, and you need to add a CHANGELOG entry.

2021-07-21 17:51 UTC, guykogus commented on Sources/SwifterSwift/Foundation/NSDecimalNumberExtensions.swift
> +    // https://gist.github.com/mattt/1ed12090d7c89f36fd28
This comment belongs at the top of the file, since it was copied from there.

2021-07-21 17:51 UTC, guykogus commented on Tests/FoundationTests/NSDecimalNumberExtensionsTests.swift
> +        XCTAssertTrue(test1 == test2)
Use `XCTAssert(Not)Equal`

2021-07-21 17:51 UTC, guykogus commented on Tests/FoundationTests/NSDecimalNumberExtensionsTests.swift
> +        XCTAssertTrue(test2 < test1)
Use `XCTAssertLessThan`

2021-08-28 16:15 UTC, closed without merging