IOS15 have failed on the old way, USES the UINavigationBarAppearance …
SwifterSwift/SwifterSwift pull request #986
Opened 2021-09-24 04:31 UTC by SunShineLOL

The old method on iOS15 is no longer valid, use UINavigationBarAppearance to set UINavigationBar

2021-09-26 22:58 UTC, emrcftci approved these changes

2021-09-26 23:03 UTC, emrcftci commented
could we declare the extension as an open? lastly we've needed to override `makeTransparent` method but couldn't.

2021-10-03 14:19 UTC, guykogus requested changes
Thanks for the update. You need to add a CHANGELOG entry and maybe some tests, if possible (although I'm not sure how).

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +            }
```suggestion
            standardAppearance.titleTextAttributes = attrs
            scrollEdgeAppearance?.titleTextAttributes = attrs
```

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +        }else{
```suggestion
        } else {
```

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +            }
```suggestion
            standardAppearance.backgroundColor = background
            standardAppearance.backgroundImage = UIImage()
            standardAppearance.titleTextAttributes = [.foregroundColor: text]

            scrollEdgeAppearance?.backgroundColor = background
            scrollEdgeAppearance?.backgroundImage = UIImage()
            scrollEdgeAppearance?.titleTextAttributes = [.foregroundColor: text]
```

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +        } else{
```suggestion
        } else {
```

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +        }else{
```suggestion
        } else {
```

2021-10-03 14:19 UTC, guykogus commented on Sources/SwifterSwift/UIKit/UINavigationBarExtensions.swift
> +        if #available(iOS 13.0, *) {
You might need to add checks for `tvOS 13.0` as well

2022-04-17 17:53 UTC, closed without merging